version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
     - "5000:5000"
    
  frontend:
    build:
      context: ./frontapp
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
